hindcast-std:
- "hindcast-std-wy2020"
- "hindcast-std-wy2021"
- "hindcast-std-wy2022"
- "hindcast-std-wy2023"
- "hindcast-std-wy2024"

hindcast-dyn-rolling:
- "hindcast-dyn-rolling-wy2020"
- "hindcast-dyn-rolling-wy2021"
- "hindcast-dyn-rolling-wy2022"
- "hindcast-dyn-rolling-wy2023"
- "hindcast-dyn-rolling-wy2024"

hindcast-dyn:
- "hindcast-dyn-wy2020"
- "hindcast-dyn-wy2021"
- "hindcast-dyn-wy2022"
- "hindcast-dyn-wy2023"
- "hindcast-dyn-wy2024"
