hindcast_dyn_old: hindcast_dyn_old
hindcast_std_old: hindcast_std_old
hindcast-dyn: hindcast-dyn
hindcast-std: hindcast-std
hindcast-dyn-2022: hindcast-dyn-2022
hindcast-dyn-spec-cap: hindcast-dyn-spec-cap
hindcast-dyn-spec-cap-rolling: hindcast-dyn-spec-cap-rolling
hindcast-dyn-spec-cap-irena: hindcast-dyn-spec-cap-irena
hindcast-dyn-spec-cap-rolling-irena: hindcast-dyn-spec-cap-rolling-irena
hindcast-dyn-rolling: hindcast-dyn-rolling