defaults:
  - config_results_concat: config_results_concat
  - _self_

network_files:
# hindcast-std:
- "hindcast-std-wy2020.nc"
- "hindcast-std-wy2021.nc"
- "hindcast-std-wy2022.nc"
- "hindcast-std-wy2023.nc"
- "hindcast-std-wy2024.nc"
# hindcast-dyn-rolling:
- "hindcast-dyn-rolling-wy2020.nc"
- "hindcast-dyn-rolling-wy2021.nc"
- "hindcast-dyn-rolling-wy2022.nc"
- "hindcast-dyn-rolling-wy2023.nc"
- "hindcast-dyn-rolling-wy2024.nc"
# hindcast-dyn:
- "hindcast-dyn-wy2020.nc"
- "hindcast-dyn-wy2021.nc"
- "hindcast-dyn-wy2022.nc"
- "hindcast-dyn-wy2023.nc"
- "hindcast-dyn-wy2024.nc"

paths:
  root: "${hydra:runtime.cwd}"
  log: "./logs"

# Merge dataframes
merge_dataframes:
- electricity_prices.csv
#- generators_dispatch.csv

# Compute scores
benchmark_score_files:
- electricity_prices.csv

metrics:
- mae
- rmse
- smape

years_list:
- 2020
- 2021
- 2022
- 2023
- 2024

api_key: YOUR-ENTSOE-API-KEY

# Per-simulation config
plot_export_format: "pdf"
exclude_countries:
  - 'MK'  # Add problematic countries here

